# Generated by Django 6.1 on 2026-09-19 10:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='ISO code, e.g. en, hi', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date', 'name']},
        ),
        migrations.AddField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(choices=[('U', 'U - Universal'), ('UA', 'UA - Parental Guidance'), ('A', 'A - Adults Only'), ('S', 'S - Special')], default='UA', max_length=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Runtime in minutes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_youtube_id',
            field=models.CharField(blank=True, help_text='Paste the YouTube URL or just the 11-character video ID.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-character YouTube video ID (not a full URL).', regex='^[A-Za-z0-9_-]{11}$')]),
        ),
        migrations.AddField(
            model_name='theater',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, help_text='Legacy free-text cast list (optional now that Cast Members are supported)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(help_text='Primary poster image', upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.language'),
        ),
        migrations.CreateModel(
            name='MovieCastCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('role_type', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer')], default='actor', max_length=20)),
                ('billing_order', models.PositiveIntegerField(default=0)),
                ('cast_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='movies.castmember')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='movies.movie')),
            ],
            options={
                'ordering': ['billing_order', 'id'],
                'unique_together': {('movie', 'cast_member', 'role_type')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_members',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieCastCredit', to='movies.castmember'),
        ),
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies/posters/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='movies.movie')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_verified_viewer', models.BooleanField(default=False, editable=False, help_text='Set automatically when the reviewer has a completed booking for this movie.')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide from public display (e.g. after moderation).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='movies.booking')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('movie', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=10)),
                ('date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='movies.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.theater')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.show'),
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.show'),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abusive or inappropriate'), ('spoiler', 'Unmarked spoiler'), ('other', 'Other')], default='other', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='movies.review')),
            ],
            options={
                'unique_together': {('review', 'reported_by')},
            },
        ),
    ]
